# Database configuration
mysql:
  host: "10.0.10.57"
  port: 3306
  user: "dbadmin"
  password: "Bedrock2026Secure"
  database: "retail_mysql"

postgres:
  host: "project-bedrock-postgres.cl8s20620zhh.us-east-1.rds.amazonaws.com"
  port: 5432

dynamodb:
  table: "project-bedrock-catalog"
  region: "us-east-1"

redis:
  host: "redis"
  port: 6379

rabbitmq:
  host: "rabbitmq"
  port: 5672
  user: "guest"
  password: "guest"

# Catalog
catalog:
  image: public.ecr.aws/aws-containers/retail-store-sample-catalog:0.4.0
  dbEndpoint: "catalog-db:3306"

# Cart
cart:
  image: public.ecr.aws/aws-containers/retail-store-sample-cart:latest

# Orders
orders:
  image: public.ecr.aws/aws-containers/retail-store-sample-orders:latest

# Checkout
checkout:
  image: public.ecr.aws/aws-containers/retail-store-sample-checkout:latest

# UI
ui:
  image: public.ecr.aws/aws-containers/retail-store-sample-ui:latest

# RabbitMQ
rabbitmq:
  image: rabbitmq:3.9-management-alpine

# Redis
redis:
  image: redis:6-alpine