apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: retail-app
spec:
  selector:
    app: catalog
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-mysql
  namespace: retail-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: catalog-mysql
  namespace: retail-app
subsets:
  - addresses:
      - ip: 10.0.10.57
    ports:
      - port: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog
  namespace: retail-app
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: mysql
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: catalog-mysql:3306
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: retail_mysql
  RETAIL_CATALOG_SEARCH_ENABLED: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: public.ecr.aws/aws-containers/retail-store-sample-catalog:1.6.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog
          env:
            - name: DB_USER
              value: "dbadmin"
            - name: DB_PASSWORD
              value: "Bedrock2026Secure"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi