apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: retail-app
spec:
  selector:
    app: checkout
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: public.ecr.aws/aws-containers/retail-store-sample-checkout:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi