apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: retail-app
spec:
  selector:
    app: orders
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: public.ecr.aws/aws-containers/retail-store-sample-orders:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi