apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: cart
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: {{ .Values.images.cart }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: carts
          env:
            - name: AWS_REGION
              value: {{ .Values.dynamodb.region | quote }}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carts
  namespace: {{ .Release.Namespace }}
data:
  RETAIL_CART_PERSISTENCE_PROVIDER: dynamodb
  RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME: {{ .Values.dynamodb.table }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: "true"