apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: checkout
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: {{ .Values.images.checkout }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: checkout
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout
  namespace: {{ .Release.Namespace }}
data:
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: redis
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: redis://checkout-redis:6379
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: http://orders:80